//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWGAfterlifeLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWGAfterlifeLauncher.StrResources", typeof(StrResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWGEmu.exe.
        /// </summary>
        internal static string ClientFilename {
            get {
                return ResourceManager.GetString("ClientFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fileserv.assistedhosting.com/swgfiles/.
        /// </summary>
        internal static string ClientFileUrl {
            get {
                return ResourceManager.GetString("ClientFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cfg.
        /// </summary>
        internal static string ConfigFileExt {
            get {
                return ResourceManager.GetString("ConfigFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing some SWG Afterlife files. Do you want to download them?.
        /// </summary>
        internal static string DownloadConfirmation {
            get {
                return ResourceManager.GetString("DownloadConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location of Game Client....
        /// </summary>
        internal static string FolderDialogTitle {
            get {
                return ResourceManager.GetString("FolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwgAfterlifeManifest.csv.
        /// </summary>
        internal static string MftFilename {
            get {
                return ResourceManager.GetString("MftFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles.
        /// </summary>
        internal static string MilesFolder {
            get {
                return ResourceManager.GetString("MilesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profiles.
        /// </summary>
        internal static string ProfileFolder {
            get {
                return ResourceManager.GetString("ProfileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screenshots.
        /// </summary>
        internal static string ScreenshotFolder {
            get {
                return ResourceManager.GetString("ScreenshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afterlife.
        /// </summary>
        internal static string ServerNameLive {
            get {
                return ResourceManager.GetString("ServerNameLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Center.
        /// </summary>
        internal static string ServerNameTC {
            get {
                return ResourceManager.GetString("ServerNameTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWGEmu_Setup.exe.
        /// </summary>
        internal static string SetupFilename {
            get {
                return ResourceManager.GetString("SetupFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the Test Center client directory. Please wait a moment....
        /// </summary>
        internal static string StatusCreatingTCFolder {
            get {
                return ResourceManager.GetString("StatusCreatingTCFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  failed to download. Please try again later..
        /// </summary>
        internal static string StatusDownloadFailed {
            get {
                return ResourceManager.GetString("StatusDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file .
        /// </summary>
        internal static string StatusDownloadingFile {
            get {
                return ResourceManager.GetString("StatusDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files are missing. Please either Check for Updates to download client files, or Select a different client folder..
        /// </summary>
        internal static string StatusFilesMissing {
            get {
                return ResourceManager.GetString("StatusFilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving the file manifest.
        /// </summary>
        internal static string StatusGettingManifest {
            get {
                return ResourceManager.GetString("StatusGettingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing quick check of files.
        /// </summary>
        internal static string StatusQuickCheck {
            get {
                return ResourceManager.GetString("StatusQuickCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning file: .
        /// </summary>
        internal static string StatusScanningFile {
            get {
                return ResourceManager.GetString("StatusScanningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tc.
        /// </summary>
        internal static string TCFolder {
            get {
                return ResourceManager.GetString("TCFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Test Center directory has not been setup yet.  Do you want to install the Test Center directory?.
        /// </summary>
        internal static string TCInstallConfirmation {
            get {
                return ResourceManager.GetString("TCInstallConfirmation", resourceCulture);
            }
        }
    }
}
